[package]
name = "regskin"
version = "0.1.2"
authors = ["rabadin <rvbadin@gmail.com>"]
edition = "2018"

[dependencies]

actix = "0.8"
actix-web = { version="1.0", features=["ssl"] }
actix-files = "0.1.5"
actix-http = "0.2.10"
regex = "1.3.1"
serde = "1.0"
tokio = "0.1.22"
serde_json = "1.0"
lazy_static = "1.4"
url = "2.1.0"

actix-web-prom = "0.1"
validator = "0.9.0"
validator_derive = "0.9.0"
log = "0.4.8"
env_logger = "0.6.2"
rand = "0.7.0"
reqwest = "0.9.20"
clokwerk = "0.2.2"
askama = "0.8"
bytes = "0.4"
